/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import com.poo.bieninmueble.controladores.ControladorPrincipal;

/**
 *
 * @author anjel
 */
public class VistaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VistaAdministrador
     */
    public VistaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTabbedPane1 = new javax.swing.JTabbedPane();
    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaClientes = new javax.swing.JTable();
    jLabel2 = new javax.swing.JLabel();
    btnDescargarClientes = new javax.swing.JButton();
    btnActualizarClientes = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jLabel6 = new javax.swing.JLabel();
    txtNombre = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    txtApellido = new javax.swing.JTextField();
    txtCorreo = new javax.swing.JTextField();
    txtIdentificacion = new javax.swing.JTextField();
    jLabel10 = new javax.swing.JLabel();
    btnRegistrarAgente = new javax.swing.JButton();
    jLabel9 = new javax.swing.JLabel();
    txtNumero = new javax.swing.JTextField();
    jPanel3 = new javax.swing.JPanel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaAgentes = new javax.swing.JTable();
    bntActualizarTablaAgentes = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    btnX = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Bienvenido administrador");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

    jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "ID", "Nombre", "Apellido", "Número telefónico", "Correo"
      }
    ));
    tablaClientes.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
    jScrollPane1.setViewportView(tablaClientes);

    jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 45, 680, 160));

    jLabel2.setText("Lista de clientes");
    jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

    btnDescargarClientes.setText("Descargar .csv");
    jPanel1.add(btnDescargarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));

    btnActualizarClientes.setText("Actualizar clientes");
    jPanel1.add(btnActualizarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

    jTabbedPane1.addTab("Ver clientes", jPanel1);

    jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel6.setBackground(new java.awt.Color(255, 255, 255));
    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel6.setText("Nombre:");
    jLabel6.setOpaque(true);
    jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 100, 20));
    jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 160, -1));

    jLabel7.setBackground(new java.awt.Color(255, 255, 255));
    jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel7.setText("Apellido:");
    jLabel7.setOpaque(true);
    jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 100, 20));

    jLabel8.setBackground(new java.awt.Color(255, 255, 255));
    jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel8.setText("Correo:");
    jLabel8.setOpaque(true);
    jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 100, 20));
    jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 160, -1));
    jPanel2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 160, -1));
    jPanel2.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 160, -1));

    jLabel10.setBackground(new java.awt.Color(255, 255, 255));
    jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel10.setText("Identificación:");
    jLabel10.setOpaque(true);
    jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 100, 20));

    btnRegistrarAgente.setText("Registrar");
    btnRegistrarAgente.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegistrarAgenteActionPerformed(evt);
      }
    });
    jPanel2.add(btnRegistrarAgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 203, 110, 40));

    jLabel9.setBackground(new java.awt.Color(255, 255, 255));
    jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel9.setText("Número:");
    jLabel9.setOpaque(true);
    jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 20));
    jPanel2.add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 160, -1));

    jTabbedPane1.addTab("Crear Agentes", jPanel2);

    tablaAgentes.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null},
        {null, null, null, null, null, null}
      },
      new String [] {
        "ID", "Nombre", "Apellido", "Teléfono", "Correo", "Cant. Prop."
      }
    ));
    jScrollPane2.setViewportView(tablaAgentes);

    bntActualizarTablaAgentes.setText("Actualizar");

    jLabel5.setText("Lista Agentes");

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(bntActualizarTablaAgentes)
        .addGap(312, 312, 312))
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(10, 10, 10)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jLabel5))
        .addContainerGap(20, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(27, 27, 27)
        .addComponent(bntActualizarTablaAgentes)
        .addGap(52, 52, 52))
    );

    jTabbedPane1.addTab("Ver Agentes", jPanel3);

    getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 720, 320));
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 20, 400));

    jLabel4.setText(" ");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 650, -1));

    btnX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnX.setForeground(new java.awt.Color(255, 51, 0));
    btnX.setText("X");
    btnX.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXActionPerformed(evt);
      }
    });
    getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 60, 30));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
    this.setVisible(false);
    ControladorPrincipal vista = new ControladorPrincipal(new VistaCredenciales());
    vista.vistaPrincipal.setVisible(true);
  }//GEN-LAST:event_btnXActionPerformed

  private void btnRegistrarAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAgenteActionPerformed
    txtIdentificacion.setText("");
    txtNombre.setText("");
    txtApellido.setText("");
    txtCorreo.setText("");
    txtNumero.setText("");
  }//GEN-LAST:event_btnRegistrarAgenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAdministrador().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton bntActualizarTablaAgentes;
  public javax.swing.JButton btnActualizarClientes;
  public javax.swing.JButton btnDescargarClientes;
  public javax.swing.JButton btnRegistrarAgente;
  public javax.swing.JButton btnX;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTabbedPane jTabbedPane1;
  public javax.swing.JTable tablaAgentes;
  public javax.swing.JTable tablaClientes;
  public javax.swing.JTextField txtApellido;
  public javax.swing.JTextField txtCorreo;
  public javax.swing.JTextField txtIdentificacion;
  public javax.swing.JTextField txtNombre;
  public javax.swing.JTextField txtNumero;
  // End of variables declaration//GEN-END:variables
}
