/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author anjel
 */
public class VistaCentroComercial extends javax.swing.JFrame {

  /**
   * Creates new form VistaCentroComercial
   */
  public VistaCentroComercial() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel36 = new javax.swing.JLabel();
    txtIdCentro = new javax.swing.JTextField();
    jLabel37 = new javax.swing.JLabel();
    comboModalidadCentro = new javax.swing.JComboBox<>();
    jLabel38 = new javax.swing.JLabel();
    txtAreaCentro = new javax.swing.JTextField();
    jLabel39 = new javax.swing.JLabel();
    txtMetroCentro = new javax.swing.JTextField();
    jLabel40 = new javax.swing.JLabel();
    txtFiscalCentro = new javax.swing.JTextField();
    jLabel41 = new javax.swing.JLabel();
    txtProvinciaCentro = new javax.swing.JComboBox<>();
    jLabel42 = new javax.swing.JLabel();
    txtCantonCentro = new javax.swing.JTextField();
    jLabel43 = new javax.swing.JLabel();
    txtDistritoCentro = new javax.swing.JTextField();
    jLabel44 = new javax.swing.JLabel();
    txtDireccionCentro = new javax.swing.JTextField();
    jLabel45 = new javax.swing.JLabel();
    comboEstadoCentro = new javax.swing.JComboBox<>();
    jLabel46 = new javax.swing.JLabel();
    txtConstruccionCentro = new javax.swing.JTextField();
    jLabel47 = new javax.swing.JLabel();
    comboEstiloCentro = new javax.swing.JComboBox<>();
    jLabel48 = new javax.swing.JLabel();
    txtTiendasCentro = new javax.swing.JTextField();
    jLabel49 = new javax.swing.JLabel();
    txtSalasCineCentro = new javax.swing.JTextField();
    jLabel51 = new javax.swing.JLabel();
    txtCadenaCentro = new javax.swing.JTextField();
    jLabel52 = new javax.swing.JLabel();
    txtWifiCentro = new javax.swing.JTextField();
    jLabel53 = new javax.swing.JLabel();
    txtEscalerasCentro = new javax.swing.JTextField();
    jLabel50 = new javax.swing.JLabel();
    jLabel54 = new javax.swing.JLabel();
    txtEspaciosCentro = new javax.swing.JTextField();
    labelImagenCentro = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaImagenesCentro = new javax.swing.JTable();
    jLabel78 = new javax.swing.JLabel();
    btnBuscarImagenCentro = new javax.swing.JButton();
    btnEliminarImagenCentro = new javax.swing.JButton();
    btnActualizarCentro = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel36.setBackground(new java.awt.Color(204, 204, 204));
    jLabel36.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel36.setText("Número de finca:");
    jLabel36.setOpaque(true);
    getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 20));

    txtIdCentro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdCentroActionPerformed(evt);
      }
    });
    getContentPane().add(txtIdCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 200, -1));

    jLabel37.setBackground(new java.awt.Color(204, 204, 204));
    jLabel37.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel37.setText("Modalidad:");
    jLabel37.setOpaque(true);
    getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 20));

    comboModalidadCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Alquiler" }));
    getContentPane().add(comboModalidadCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 200, -1));

    jLabel38.setBackground(new java.awt.Color(204, 204, 204));
    jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel38.setText("Área del terreno:");
    jLabel38.setOpaque(true);
    getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 20));
    getContentPane().add(txtAreaCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 200, -1));

    jLabel39.setBackground(new java.awt.Color(204, 204, 204));
    jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel39.setText("Valor metro cuadrado:");
    jLabel39.setOpaque(true);
    getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 20));
    getContentPane().add(txtMetroCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 200, -1));

    jLabel40.setBackground(new java.awt.Color(204, 204, 204));
    jLabel40.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel40.setText("Valor fiscal:");
    jLabel40.setOpaque(true);
    getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 20));
    getContentPane().add(txtFiscalCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 200, -1));

    jLabel41.setBackground(new java.awt.Color(204, 204, 204));
    jLabel41.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel41.setText("Provincia:");
    jLabel41.setOpaque(true);
    getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 130, 20));

    txtProvinciaCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Limón", "Puntarenas" }));
    getContentPane().add(txtProvinciaCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 200, -1));

    jLabel42.setBackground(new java.awt.Color(204, 204, 204));
    jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel42.setText("Cantón:");
    jLabel42.setOpaque(true);
    getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 130, 20));
    getContentPane().add(txtCantonCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 200, -1));

    jLabel43.setBackground(new java.awt.Color(204, 204, 204));
    jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel43.setText("Distrito:");
    jLabel43.setOpaque(true);
    getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 130, 20));
    getContentPane().add(txtDistritoCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 200, -1));

    jLabel44.setBackground(new java.awt.Color(204, 204, 204));
    jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel44.setText("Dirección exacta:");
    jLabel44.setOpaque(true);
    getContentPane().add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 130, 20));
    getContentPane().add(txtDireccionCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 340, 200, -1));

    jLabel45.setBackground(new java.awt.Color(204, 204, 204));
    jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel45.setText("Estado:");
    jLabel45.setOpaque(true);
    getContentPane().add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 130, 20));

    comboEstadoCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
    getContentPane().add(comboEstadoCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 200, -1));

    jLabel46.setBackground(new java.awt.Color(204, 204, 204));
    jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel46.setText("Área de construcción:");
    jLabel46.setOpaque(true);
    getContentPane().add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 130, 20));
    getContentPane().add(txtConstruccionCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 420, 200, -1));

    jLabel47.setBackground(new java.awt.Color(204, 204, 204));
    jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel47.setText("Estilo de construcción:");
    jLabel47.setOpaque(true);
    getContentPane().add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 220, 20));

    comboEstiloCentro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gótico", "Contemporáneo", "Barroco", "Modernista", "Art-Deco" }));
    getContentPane().add(comboEstiloCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 170, -1));

    jLabel48.setBackground(new java.awt.Color(204, 204, 204));
    jLabel48.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel48.setText("Cantidad de tiendas:");
    jLabel48.setOpaque(true);
    getContentPane().add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 220, 20));
    getContentPane().add(txtTiendasCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 60, 170, -1));

    jLabel49.setBackground(new java.awt.Color(204, 204, 204));
    jLabel49.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel49.setText("Cantidad salas de cine:");
    jLabel49.setOpaque(true);
    getContentPane().add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 220, 20));
    getContentPane().add(txtSalasCineCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 170, -1));

    jLabel51.setBackground(new java.awt.Color(204, 204, 204));
    jLabel51.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel51.setText("Cadena de cine:");
    jLabel51.setOpaque(true);
    getContentPane().add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, 220, 20));
    getContentPane().add(txtCadenaCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 170, -1));

    jLabel52.setBackground(new java.awt.Color(204, 204, 204));
    jLabel52.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel52.setText("Cantidad de Hotspot WiFi:");
    jLabel52.setOpaque(true);
    getContentPane().add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 220, 20));
    getContentPane().add(txtWifiCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 170, -1));

    jLabel53.setBackground(new java.awt.Color(204, 204, 204));
    jLabel53.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel53.setText("Cantidad escaleras electricas:");
    jLabel53.setOpaque(true);
    getContentPane().add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 220, 220, 20));
    getContentPane().add(txtEscalerasCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 170, -1));

    jLabel50.setBackground(new java.awt.Color(204, 204, 204));
    jLabel50.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel50.setText("Cantidad espacios disponibles");
    jLabel50.setOpaque(true);
    getContentPane().add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 220, 20));

    jLabel54.setBackground(new java.awt.Color(204, 204, 204));
    jLabel54.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel54.setText("para personas con movilidad reducida:");
    jLabel54.setOpaque(true);
    getContentPane().add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 220, 20));
    getContentPane().add(txtEspaciosCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 170, 40));

    labelImagenCentro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getContentPane().add(labelImagenCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 360, 250, 130));

    tablaImagenesCentro.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Imagenes"
      }
    ));
    tablaImagenesCentro.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaImagenesCentroMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tablaImagenesCentro);

    getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 270, 100));

    jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel78.setText("Imágenes:");
    getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 320, 30));

    btnBuscarImagenCentro.setText("Buscar imagen");
    btnBuscarImagenCentro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarImagenCentroActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarImagenCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 120, -1));

    btnEliminarImagenCentro.setText("Eliminar Imagen");
    btnEliminarImagenCentro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarImagenCentroActionPerformed(evt);
      }
    });
    getContentPane().add(btnEliminarImagenCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, 140, -1));

    btnActualizarCentro.setText("Actualizar");
    btnActualizarCentro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnActualizarCentroActionPerformed(evt);
      }
    });
    getContentPane().add(btnActualizarCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 520, 120, 40));

    jButton1.setForeground(new java.awt.Color(255, 0, 51));
    jButton1.setText("X");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 50, -1));
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 570));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtIdCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCentroActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdCentroActionPerformed

  private void tablaImagenesCentroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaImagenesCentroMouseClicked
    int fila = tablaImagenesCentro.getSelectedRow();
    TableModel modelo = tablaImagenesCentro.getModel();
    byte[] archivoImagen = (byte[]) modelo.getValueAt(fila, 0);

    ImageIcon imagenIcon = new ImageIcon(new ImageIcon(archivoImagen).getImage().getScaledInstance(labelImagenCentro.getWidth(), labelImagenCentro.getHeight()
      , Image.SCALE_SMOOTH));
  labelImagenCentro.setIcon(imagenIcon);
  }//GEN-LAST:event_tablaImagenesCentroMouseClicked

  private void btnBuscarImagenCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenCentroActionPerformed
    byte[] imagenLote;
    String archivoImagen;
    JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);

    File archivo = chooser.getSelectedFile();
    archivoImagen = archivo.getAbsolutePath();

    File imagen = new File(archivoImagen);
    FileInputStream fis;

    try {
      fis = new FileInputStream(imagen);

      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];

      for (int j; (j = fis.read(buffer)) != -1;) {
        bos.write(buffer, 0, j);
      }
      imagenLote = bos.toByteArray();
      DefaultTableModel modelo = (DefaultTableModel) tablaImagenesCentro.getModel();
      modelo.addRow(new Object[]{imagenLote});
    } catch (IOException ex) {
      Logger.getLogger(VistaLote.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_btnBuscarImagenCentroActionPerformed

  private void btnEliminarImagenCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImagenCentroActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tablaImagenesCentro.getModel();
    int fila = tablaImagenesCentro.getSelectedRow();
    modelo.removeRow(fila);
    labelImagenCentro.setIcon(null);
    labelImagenCentro.revalidate();
  }//GEN-LAST:event_btnEliminarImagenCentroActionPerformed

  private void btnActualizarCentroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCentroActionPerformed

  }//GEN-LAST:event_btnActualizarCentroActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaCentroComercial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VistaCentroComercial().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnActualizarCentro;
  public javax.swing.JButton btnBuscarImagenCentro;
  public javax.swing.JButton btnEliminarImagenCentro;
  public javax.swing.JComboBox<String> comboEstadoCentro;
  public javax.swing.JComboBox<String> comboEstiloCentro;
  public javax.swing.JComboBox<String> comboModalidadCentro;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel36;
  public javax.swing.JLabel jLabel37;
  public javax.swing.JLabel jLabel38;
  public javax.swing.JLabel jLabel39;
  public javax.swing.JLabel jLabel40;
  public javax.swing.JLabel jLabel41;
  public javax.swing.JLabel jLabel42;
  public javax.swing.JLabel jLabel43;
  public javax.swing.JLabel jLabel44;
  private javax.swing.JLabel jLabel45;
  private javax.swing.JLabel jLabel46;
  private javax.swing.JLabel jLabel47;
  public javax.swing.JLabel jLabel48;
  public javax.swing.JLabel jLabel49;
  public javax.swing.JLabel jLabel50;
  public javax.swing.JLabel jLabel51;
  public javax.swing.JLabel jLabel52;
  public javax.swing.JLabel jLabel53;
  public javax.swing.JLabel jLabel54;
  private javax.swing.JLabel jLabel78;
  public javax.swing.JScrollPane jScrollPane2;
  public javax.swing.JLabel labelImagenCentro;
  public javax.swing.JTable tablaImagenesCentro;
  public javax.swing.JTextField txtAreaCentro;
  public javax.swing.JTextField txtCadenaCentro;
  public javax.swing.JTextField txtCantonCentro;
  public javax.swing.JTextField txtConstruccionCentro;
  public javax.swing.JTextField txtDireccionCentro;
  public javax.swing.JTextField txtDistritoCentro;
  public javax.swing.JTextField txtEscalerasCentro;
  public javax.swing.JTextField txtEspaciosCentro;
  public javax.swing.JTextField txtFiscalCentro;
  public javax.swing.JTextField txtIdCentro;
  public javax.swing.JTextField txtMetroCentro;
  public javax.swing.JComboBox<String> txtProvinciaCentro;
  public javax.swing.JTextField txtSalasCineCentro;
  public javax.swing.JTextField txtTiendasCentro;
  public javax.swing.JTextField txtWifiCentro;
  // End of variables declaration//GEN-END:variables
}
