/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import com.poo.bieninmueble.controladores.ControladorPrincipal;
import javax.swing.table.TableModel;

/**
 *
 * @author anjel
 */
public class VistaAgente extends javax.swing.JFrame {

    /**
     * Creates new form VistaAgente
     */
    public VistaAgente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel8 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    btnSalirSesion = new javax.swing.JButton();
    lblImagenPropiedad = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    btnLote = new javax.swing.JButton();
    btnCentro = new javax.swing.JButton();
    btnCasa = new javax.swing.JButton();
    btnEdificio = new javax.swing.JButton();
    comboFiltroPropiedad = new javax.swing.JComboBox<>();
    txtCriterioFiltro = new javax.swing.JTextField();
    btnFiltrar = new javax.swing.JButton();
    jLabel79 = new javax.swing.JLabel();
    txtMenor = new javax.swing.JTextField();
    txtMayor = new javax.swing.JTextField();
    jLabel81 = new javax.swing.JLabel();
    btnBuscarRango = new javax.swing.JButton();
    jLabel82 = new javax.swing.JLabel();
    jScrollPane7 = new javax.swing.JScrollPane();
    tablaPropiedades = new javax.swing.JTable();
    jLabel83 = new javax.swing.JLabel();
    jLabel80 = new javax.swing.JLabel();
    jLabel84 = new javax.swing.JLabel();
    lblIdPropiedad = new javax.swing.JLabel();
    btnVerPropiedad = new javax.swing.JButton();
    btnEditarPropiedad = new javax.swing.JButton();
    btnEliminarPropiedad = new javax.swing.JButton();
    btnConsultarProspectos = new javax.swing.JButton();
    jLabel85 = new javax.swing.JLabel();
    jLabel86 = new javax.swing.JLabel();
    jLabel1 = new javax.swing.JLabel();
    jMenuBar1 = new javax.swing.JMenuBar();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel3.setText(" ");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 40, -1));

    btnSalirSesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    btnSalirSesion.setForeground(new java.awt.Color(255, 0, 0));
    btnSalirSesion.setText("X");
    btnSalirSesion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnSalirSesionActionPerformed(evt);
      }
    });
    getContentPane().add(btnSalirSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, -1, -1));

    lblImagenPropiedad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getContentPane().add(lblImagenPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 260, 180));

    jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
    jLabel7.setText("Bienvenido/a agente");
    getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

    btnLote.setText("Crear Lote");
    getContentPane().add(btnLote, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, 120, -1));

    btnCentro.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
    btnCentro.setText("Crear Centro Comercial");
    getContentPane().add(btnCentro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 490, 160, -1));

    btnCasa.setText("Crear Casa");
    getContentPane().add(btnCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 490, 120, -1));

    btnEdificio.setText("Crear Edificio");
    getContentPane().add(btnEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 160, -1));

    comboFiltroPropiedad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Modalidad", "Provincia", "Todas" }));
    comboFiltroPropiedad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        comboFiltroPropiedadActionPerformed(evt);
      }
    });
    getContentPane().add(comboFiltroPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 90, 30));

    txtCriterioFiltro.setText("Inserte el criterio...");
    txtCriterioFiltro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtCriterioFiltroActionPerformed(evt);
      }
    });
    getContentPane().add(txtCriterioFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 180, 30));

    btnFiltrar.setText("Buscar");
    btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnFiltrarActionPerformed(evt);
      }
    });
    getContentPane().add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 80, 30));

    jLabel79.setBackground(new java.awt.Color(255, 255, 255));
    jLabel79.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel79.setText("Fitrar por:");
    jLabel79.setOpaque(true);
    getContentPane().add(jLabel79, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 30));

    txtMenor.setText("Menor");
    getContentPane().add(txtMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 40, 60, 30));

    txtMayor.setText("Mayor");
    getContentPane().add(txtMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 60, 30));

    jLabel81.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel81.setText("a");
    getContentPane().add(jLabel81, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, 10, 30));

    btnBuscarRango.setText("Buscar precio");
    btnBuscarRango.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarRangoActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, 120, 30));

    jLabel82.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel82.setText("Información bienes inmuebles");
    getContentPane().add(jLabel82, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

    tablaPropiedades.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "ID", "Tipo", "Modalidad", "Precio", "Provincia"
      }
    ));
    tablaPropiedades.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaPropiedadesMouseClicked(evt);
      }
    });
    jScrollPane7.setViewportView(tablaPropiedades);

    getContentPane().add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 950, 150));

    jLabel83.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel83.setText("Propiedad seleccionada: ");
    getContentPane().add(jLabel83, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, 20));

    jLabel80.setBackground(new java.awt.Color(255, 255, 255));
    jLabel80.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
    jLabel80.setText("Filtrar por rango de precio:");
    jLabel80.setOpaque(true);
    getContentPane().add(jLabel80, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 440, 30));

    jLabel84.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel84.setText("Imagen:");
    getContentPane().add(jLabel84, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, 20));

    lblIdPropiedad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    getContentPane().add(lblIdPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 60, 30));

    btnVerPropiedad.setText("Ver");
    getContentPane().add(btnVerPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 310, 90, -1));

    btnEditarPropiedad.setText("Editar");
    getContentPane().add(btnEditarPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 90, -1));

    btnEliminarPropiedad.setText("Eliminar");
    btnEliminarPropiedad.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarPropiedadActionPerformed(evt);
      }
    });
    getContentPane().add(btnEliminarPropiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 310, 80, -1));

    btnConsultarProspectos.setText("Consultar Prospectos");
    btnConsultarProspectos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnConsultarProspectosActionPerformed(evt);
      }
    });
    getContentPane().add(btnConsultarProspectos, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 350, 290, -1));

    jLabel85.setBackground(new java.awt.Color(255, 255, 255));
    jLabel85.setOpaque(true);
    getContentPane().add(jLabel85, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 320, 110));

    jLabel86.setBackground(new java.awt.Color(255, 255, 255));
    jLabel86.setOpaque(true);
    getContentPane().add(jLabel86, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 290, 320, 100));
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 980, 550));
    setJMenuBar(jMenuBar1);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnSalirSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirSesionActionPerformed
      this.setVisible(false);
      ControladorPrincipal vista = new ControladorPrincipal(new VistaCredenciales());
      vista.vistaPrincipal.setVisible(true);
    }//GEN-LAST:event_btnSalirSesionActionPerformed

  private void txtCriterioFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCriterioFiltroActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtCriterioFiltroActionPerformed

  private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
    this.txtCriterioFiltro.setText("Inserte el criterio...");
    this.txtMayor.setText("Mayor");
    this.txtMenor.setText("Menor");
    this.lblIdPropiedad.setText("");
    this.lblImagenPropiedad.setIcon(null);
    this.lblImagenPropiedad.revalidate();
  }//GEN-LAST:event_btnFiltrarActionPerformed

  private void btnBuscarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRangoActionPerformed
    this.txtCriterioFiltro.setText("Inserte el criterio...");
    this.txtMayor.setText("Mayor");
    this.txtMenor.setText("Menor");
    this.lblIdPropiedad.setText("");
    this.lblImagenPropiedad.setIcon(null);
    this.lblImagenPropiedad.revalidate();
  }//GEN-LAST:event_btnBuscarRangoActionPerformed

  private void tablaPropiedadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPropiedadesMouseClicked
    TableModel modelo = this.tablaPropiedades.getModel();
    int index = this.tablaPropiedades.getSelectedRow();
    String numFinca = modelo.getValueAt(index, 0).toString();
    
    this.lblIdPropiedad.setText(numFinca);
  }//GEN-LAST:event_tablaPropiedadesMouseClicked

  private void btnConsultarProspectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarProspectosActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnConsultarProspectosActionPerformed

  private void comboFiltroPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboFiltroPropiedadActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_comboFiltroPropiedadActionPerformed

  private void btnEliminarPropiedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPropiedadActionPerformed
    this.lblIdPropiedad.setText("");
    this.lblImagenPropiedad.setIcon(null);
    this.lblImagenPropiedad.revalidate();
  }//GEN-LAST:event_btnEliminarPropiedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgente().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnBuscarRango;
  public javax.swing.JButton btnCasa;
  public javax.swing.JButton btnCentro;
  public javax.swing.JButton btnConsultarProspectos;
  public javax.swing.JButton btnEdificio;
  public javax.swing.JButton btnEditarPropiedad;
  public javax.swing.JButton btnEliminarPropiedad;
  public javax.swing.JButton btnFiltrar;
  public javax.swing.JButton btnLote;
  public javax.swing.JButton btnSalirSesion;
  public javax.swing.JButton btnVerPropiedad;
  public javax.swing.JComboBox<String> comboFiltroPropiedad;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel7;
  public javax.swing.JLabel jLabel79;
  private javax.swing.JLabel jLabel8;
  public javax.swing.JLabel jLabel80;
  public javax.swing.JLabel jLabel81;
  public javax.swing.JLabel jLabel82;
  public javax.swing.JLabel jLabel83;
  public javax.swing.JLabel jLabel84;
  private javax.swing.JLabel jLabel85;
  private javax.swing.JLabel jLabel86;
  private javax.swing.JMenuBar jMenuBar1;
  public javax.swing.JScrollPane jScrollPane7;
  public javax.swing.JLabel lblIdPropiedad;
  public javax.swing.JLabel lblImagenPropiedad;
  public javax.swing.JTable tablaPropiedades;
  public javax.swing.JTextField txtCriterioFiltro;
  public javax.swing.JTextField txtMayor;
  public javax.swing.JTextField txtMenor;
  // End of variables declaration//GEN-END:variables
}
