/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author anjel
 */
public class VistaCasa extends javax.swing.JFrame {

  /**
   * Creates new form VistaCasa
   */
  public VistaCasa() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    labelImagenCasa = new javax.swing.JLabel();
    txtAnnoCasa = new javax.swing.JTextField();
    jLabel35 = new javax.swing.JLabel();
    jLabel34 = new javax.swing.JLabel();
    txtColorCasa = new javax.swing.JTextField();
    jLabel33 = new javax.swing.JLabel();
    txtNivelesCasa = new javax.swing.JTextField();
    jLabel32 = new javax.swing.JLabel();
    comboEstiloCasa = new javax.swing.JComboBox<>();
    txtIdCasa = new javax.swing.JTextField();
    jLabel21 = new javax.swing.JLabel();
    jLabel22 = new javax.swing.JLabel();
    comboModalidadCasa = new javax.swing.JComboBox<>();
    jLabel23 = new javax.swing.JLabel();
    txtAreaCasa = new javax.swing.JTextField();
    jLabel24 = new javax.swing.JLabel();
    txtMetroCasa = new javax.swing.JTextField();
    jLabel25 = new javax.swing.JLabel();
    txtFiscalCasa = new javax.swing.JTextField();
    jLabel26 = new javax.swing.JLabel();
    txtProvinciaCasa = new javax.swing.JComboBox<>();
    jLabel27 = new javax.swing.JLabel();
    txtCantonCasa = new javax.swing.JTextField();
    jLabel28 = new javax.swing.JLabel();
    txtDistritoCasa = new javax.swing.JTextField();
    jLabel29 = new javax.swing.JLabel();
    txtDireccionCasa = new javax.swing.JTextField();
    jLabel30 = new javax.swing.JLabel();
    comboEstadoCasa = new javax.swing.JComboBox<>();
    jLabel31 = new javax.swing.JLabel();
    txtConstruccionCasa = new javax.swing.JTextField();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaImagenesCasa = new javax.swing.JTable();
    jLabel78 = new javax.swing.JLabel();
    btnBuscarImagenCasa = new javax.swing.JButton();
    btnEliminarImagenCasa = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    btnActualizarCasa = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    labelImagenCasa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getContentPane().add(labelImagenCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 230, 230, 130));
    getContentPane().add(txtAnnoCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, 170, -1));

    jLabel35.setBackground(new java.awt.Color(204, 204, 204));
    jLabel35.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel35.setText("Año de construcción:");
    jLabel35.setOpaque(true);
    getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 150, 20));

    jLabel34.setBackground(new java.awt.Color(204, 204, 204));
    jLabel34.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel34.setText("Color:");
    jLabel34.setOpaque(true);
    getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 150, 20));
    getContentPane().add(txtColorCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 170, -1));

    jLabel33.setBackground(new java.awt.Color(204, 204, 204));
    jLabel33.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel33.setText("Cantidad de niveles:");
    jLabel33.setOpaque(true);
    getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 150, 20));
    getContentPane().add(txtNivelesCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 170, -1));

    jLabel32.setBackground(new java.awt.Color(204, 204, 204));
    jLabel32.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel32.setText("Estilo de construcción:");
    jLabel32.setOpaque(true);
    getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 150, 20));

    comboEstiloCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gótico", "Contemporáneo", "Barroco", "Modernista", "Art-Deco" }));
    getContentPane().add(comboEstiloCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 170, -1));

    txtIdCasa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdCasaActionPerformed(evt);
      }
    });
    getContentPane().add(txtIdCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, -1));

    jLabel21.setBackground(new java.awt.Color(204, 204, 204));
    jLabel21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel21.setText("Número de finca:");
    jLabel21.setOpaque(true);
    getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 20));

    jLabel22.setBackground(new java.awt.Color(204, 204, 204));
    jLabel22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel22.setText("Modalidad:");
    jLabel22.setOpaque(true);
    getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 20));

    comboModalidadCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Alquiler" }));
    getContentPane().add(comboModalidadCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

    jLabel23.setBackground(new java.awt.Color(204, 204, 204));
    jLabel23.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel23.setText("Área del terreno:");
    jLabel23.setOpaque(true);
    getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 20));
    getContentPane().add(txtAreaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, -1));

    jLabel24.setBackground(new java.awt.Color(204, 204, 204));
    jLabel24.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel24.setText("Valor metro cuadrado:");
    jLabel24.setOpaque(true);
    getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 20));
    getContentPane().add(txtMetroCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, -1));

    jLabel25.setBackground(new java.awt.Color(204, 204, 204));
    jLabel25.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel25.setText("Valor fiscal:");
    jLabel25.setOpaque(true);
    getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 20));
    getContentPane().add(txtFiscalCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, -1));

    jLabel26.setBackground(new java.awt.Color(204, 204, 204));
    jLabel26.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel26.setText("Provincia:");
    jLabel26.setOpaque(true);
    getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 20));

    txtProvinciaCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Limón", "Puntarenas" }));
    getContentPane().add(txtProvinciaCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, -1));

    jLabel27.setBackground(new java.awt.Color(204, 204, 204));
    jLabel27.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel27.setText("Cantón:");
    jLabel27.setOpaque(true);
    getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));
    getContentPane().add(txtCantonCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, -1));

    jLabel28.setBackground(new java.awt.Color(204, 204, 204));
    jLabel28.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel28.setText("Distrito:");
    jLabel28.setOpaque(true);
    getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 20));
    getContentPane().add(txtDistritoCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, -1));

    jLabel29.setBackground(new java.awt.Color(204, 204, 204));
    jLabel29.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel29.setText("Dirección exacta:");
    jLabel29.setOpaque(true);
    getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 20));
    getContentPane().add(txtDireccionCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 200, -1));

    jLabel30.setBackground(new java.awt.Color(204, 204, 204));
    jLabel30.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel30.setText("Estado:");
    jLabel30.setOpaque(true);
    getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 20));

    comboEstadoCasa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
    getContentPane().add(comboEstadoCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 200, -1));

    jLabel31.setBackground(new java.awt.Color(204, 204, 204));
    jLabel31.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel31.setText("Área de construcción:");
    jLabel31.setOpaque(true);
    getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 130, 20));
    getContentPane().add(txtConstruccionCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 200, -1));

    tablaImagenesCasa.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Imagenes"
      }
    ));
    tablaImagenesCasa.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaImagenesCasaMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tablaImagenesCasa);

    getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 270, 100));

    jLabel78.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel78.setText("Imágenes:");
    getContentPane().add(jLabel78, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 200, 320, 30));

    btnBuscarImagenCasa.setText("Buscar imagen");
    btnBuscarImagenCasa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarImagenCasaActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarImagenCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 120, -1));

    btnEliminarImagenCasa.setText("Eliminar Imagen");
    btnEliminarImagenCasa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarImagenCasaActionPerformed(evt);
      }
    });
    getContentPane().add(btnEliminarImagenCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 140, -1));

    jButton1.setForeground(new java.awt.Color(255, 0, 51));
    jButton1.setText("X");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, 50, -1));

    btnActualizarCasa.setText("Actualizar");
    btnActualizarCasa.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnActualizarCasaActionPerformed(evt);
      }
    });
    getContentPane().add(btnActualizarCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 460, -1, -1));
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 500));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtIdCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdCasaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdCasaActionPerformed

  private void tablaImagenesCasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaImagenesCasaMouseClicked
    int fila = tablaImagenesCasa.getSelectedRow();
    TableModel modelo = tablaImagenesCasa.getModel();
    byte[] archivoImagen = (byte[]) modelo.getValueAt(fila, 0);

    ImageIcon imagenIcon = new ImageIcon(new ImageIcon(archivoImagen).getImage().getScaledInstance(labelImagenCasa.getWidth(), labelImagenCasa.getHeight()
      , Image.SCALE_SMOOTH));
  labelImagenCasa.setIcon(imagenIcon);
  }//GEN-LAST:event_tablaImagenesCasaMouseClicked

  private void btnBuscarImagenCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenCasaActionPerformed
    byte[] imagenLote;
    String archivoImagen;
    JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);

    File archivo = chooser.getSelectedFile();
    archivoImagen = archivo.getAbsolutePath();

    File imagen = new File(archivoImagen);
    FileInputStream fis;

    try {
      fis = new FileInputStream(imagen);

      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];

      for (int j; (j = fis.read(buffer)) != -1;) {
        bos.write(buffer, 0, j);
      }
      imagenLote = bos.toByteArray();
      DefaultTableModel modelo = (DefaultTableModel) tablaImagenesCasa.getModel();
      modelo.addRow(new Object[]{imagenLote});
    } catch (IOException ex) {
      Logger.getLogger(VistaLote.class.getName()).log(Level.SEVERE, null, ex);
    }

  }//GEN-LAST:event_btnBuscarImagenCasaActionPerformed

  private void btnEliminarImagenCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImagenCasaActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tablaImagenesCasa.getModel();
    int fila = tablaImagenesCasa.getSelectedRow();
    modelo.removeRow(fila);
    labelImagenCasa.setIcon(null);
    labelImagenCasa.revalidate();
  }//GEN-LAST:event_btnEliminarImagenCasaActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  private void btnActualizarCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarCasaActionPerformed

  }//GEN-LAST:event_btnActualizarCasaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaCasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VistaCasa().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnActualizarCasa;
  public javax.swing.JButton btnBuscarImagenCasa;
  public javax.swing.JButton btnEliminarImagenCasa;
  public javax.swing.JComboBox<String> comboEstadoCasa;
  public javax.swing.JComboBox<String> comboEstiloCasa;
  public javax.swing.JComboBox<String> comboModalidadCasa;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel21;
  public javax.swing.JLabel jLabel22;
  public javax.swing.JLabel jLabel23;
  public javax.swing.JLabel jLabel24;
  public javax.swing.JLabel jLabel25;
  public javax.swing.JLabel jLabel26;
  public javax.swing.JLabel jLabel27;
  public javax.swing.JLabel jLabel28;
  public javax.swing.JLabel jLabel29;
  private javax.swing.JLabel jLabel30;
  private javax.swing.JLabel jLabel31;
  private javax.swing.JLabel jLabel32;
  private javax.swing.JLabel jLabel33;
  private javax.swing.JLabel jLabel34;
  private javax.swing.JLabel jLabel35;
  private javax.swing.JLabel jLabel78;
  public javax.swing.JScrollPane jScrollPane2;
  public javax.swing.JLabel labelImagenCasa;
  public javax.swing.JTable tablaImagenesCasa;
  public javax.swing.JTextField txtAnnoCasa;
  public javax.swing.JTextField txtAreaCasa;
  public javax.swing.JTextField txtCantonCasa;
  public javax.swing.JTextField txtColorCasa;
  public javax.swing.JTextField txtConstruccionCasa;
  public javax.swing.JTextField txtDireccionCasa;
  public javax.swing.JTextField txtDistritoCasa;
  public javax.swing.JTextField txtFiscalCasa;
  public javax.swing.JTextField txtIdCasa;
  public javax.swing.JTextField txtMetroCasa;
  public javax.swing.JTextField txtNivelesCasa;
  public javax.swing.JComboBox<String> txtProvinciaCasa;
  // End of variables declaration//GEN-END:variables
}
