/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author anjel
 */
public class VistaEdificio extends javax.swing.JFrame {

  /**
   * Creates new form VistaEdificio
   */
  public VistaEdificio() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    txtIdEdificio = new javax.swing.JTextField();
    jLabel55 = new javax.swing.JLabel();
    jLabel56 = new javax.swing.JLabel();
    comboModalidadEdificio = new javax.swing.JComboBox<>();
    jLabel57 = new javax.swing.JLabel();
    txtAreaEdificio = new javax.swing.JTextField();
    jLabel58 = new javax.swing.JLabel();
    txtMetroEdificio = new javax.swing.JTextField();
    jLabel59 = new javax.swing.JLabel();
    txtFiscalEdificio = new javax.swing.JTextField();
    jLabel60 = new javax.swing.JLabel();
    txtProvinciaEdificio = new javax.swing.JComboBox<>();
    jLabel61 = new javax.swing.JLabel();
    txtCantonEdificio = new javax.swing.JTextField();
    jLabel62 = new javax.swing.JLabel();
    txtDistritoEdificio = new javax.swing.JTextField();
    jLabel63 = new javax.swing.JLabel();
    txtDireccionEdificio = new javax.swing.JTextField();
    jLabel64 = new javax.swing.JLabel();
    comboEstadoEdificio = new javax.swing.JComboBox<>();
    jLabel65 = new javax.swing.JLabel();
    txtConstruccionEdificio = new javax.swing.JTextField();
    jLabel67 = new javax.swing.JLabel();
    txtAlturaEdificio = new javax.swing.JTextField();
    jLabel68 = new javax.swing.JLabel();
    comboEstiloEdificio = new javax.swing.JComboBox<>();
    jLabel69 = new javax.swing.JLabel();
    comboPiscinaEdificio = new javax.swing.JComboBox<>();
    jLabel70 = new javax.swing.JLabel();
    comboRanchoEdificio = new javax.swing.JComboBox<>();
    jLabel72 = new javax.swing.JLabel();
    txtVisitasEdificio = new javax.swing.JTextField();
    jLabel75 = new javax.swing.JLabel();
    jLabel74 = new javax.swing.JLabel();
    txtResidenciasEdificio = new javax.swing.JTextField();
    jLabel66 = new javax.swing.JLabel();
    txtZonasEdificio = new javax.swing.JTextField();
    comboNivelEdificio = new javax.swing.JComboBox<>();
    btnAgregarNivelEdificio = new javax.swing.JButton();
    jScrollPane6 = new javax.swing.JScrollPane();
    tablaNivelesEdificio = new javax.swing.JTable();
    btnEliminarNivel = new javax.swing.JButton();
    jLabel71 = new javax.swing.JLabel();
    labelImagenEdificio = new javax.swing.JLabel();
    btnActualizarEdificio = new javax.swing.JButton();
    jScrollPane2 = new javax.swing.JScrollPane();
    tablaImagenesEdificio = new javax.swing.JTable();
    btnBuscarImagenEdificio = new javax.swing.JButton();
    btnEliminarImagenEdificio = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jLabel1 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    txtIdEdificio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        txtIdEdificioActionPerformed(evt);
      }
    });
    getContentPane().add(txtIdEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 200, -1));

    jLabel55.setBackground(new java.awt.Color(204, 204, 204));
    jLabel55.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel55.setText("Número de finca:");
    jLabel55.setOpaque(true);
    getContentPane().add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 130, 20));

    jLabel56.setBackground(new java.awt.Color(204, 204, 204));
    jLabel56.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel56.setText("Modalidad:");
    jLabel56.setOpaque(true);
    getContentPane().add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 130, 20));

    comboModalidadEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Venta", "Alquiler" }));
    getContentPane().add(comboModalidadEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 200, -1));

    jLabel57.setBackground(new java.awt.Color(204, 204, 204));
    jLabel57.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel57.setText("Área del terreno:");
    jLabel57.setOpaque(true);
    getContentPane().add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 130, 20));
    getContentPane().add(txtAreaEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 200, -1));

    jLabel58.setBackground(new java.awt.Color(204, 204, 204));
    jLabel58.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel58.setText("Valor metro cuadrado:");
    jLabel58.setOpaque(true);
    getContentPane().add(jLabel58, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, 20));
    getContentPane().add(txtMetroEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 200, -1));

    jLabel59.setBackground(new java.awt.Color(204, 204, 204));
    jLabel59.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel59.setText("Valor fiscal:");
    jLabel59.setOpaque(true);
    getContentPane().add(jLabel59, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 130, 20));
    getContentPane().add(txtFiscalEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 200, -1));

    jLabel60.setBackground(new java.awt.Color(204, 204, 204));
    jLabel60.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel60.setText("Provincia:");
    jLabel60.setOpaque(true);
    getContentPane().add(jLabel60, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 130, 20));

    txtProvinciaEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San José", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Limón", "Puntarenas" }));
    getContentPane().add(txtProvinciaEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 200, -1));

    jLabel61.setBackground(new java.awt.Color(204, 204, 204));
    jLabel61.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel61.setText("Cantón:");
    jLabel61.setOpaque(true);
    getContentPane().add(jLabel61, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));
    getContentPane().add(txtCantonEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 200, -1));

    jLabel62.setBackground(new java.awt.Color(204, 204, 204));
    jLabel62.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel62.setText("Distrito:");
    jLabel62.setOpaque(true);
    getContentPane().add(jLabel62, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 130, 20));
    getContentPane().add(txtDistritoEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 200, -1));

    jLabel63.setBackground(new java.awt.Color(204, 204, 204));
    jLabel63.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel63.setText("Dirección exacta:");
    jLabel63.setOpaque(true);
    getContentPane().add(jLabel63, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 130, 20));
    getContentPane().add(txtDireccionEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 200, -1));

    jLabel64.setBackground(new java.awt.Color(204, 204, 204));
    jLabel64.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel64.setText("Estado:");
    jLabel64.setOpaque(true);
    getContentPane().add(jLabel64, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 130, 20));

    comboEstadoEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activo", "Inactivo" }));
    getContentPane().add(comboEstadoEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 400, 200, -1));

    jLabel65.setBackground(new java.awt.Color(204, 204, 204));
    jLabel65.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel65.setText("Área de construcción:");
    jLabel65.setOpaque(true);
    getContentPane().add(jLabel65, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 130, 20));
    getContentPane().add(txtConstruccionEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 200, -1));

    jLabel67.setBackground(new java.awt.Color(204, 204, 204));
    jLabel67.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel67.setText("Altura:");
    jLabel67.setOpaque(true);
    getContentPane().add(jLabel67, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 130, 20));
    getContentPane().add(txtAlturaEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 200, -1));

    jLabel68.setBackground(new java.awt.Color(204, 204, 204));
    jLabel68.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel68.setText("Estilo de construcción:");
    jLabel68.setOpaque(true);
    getContentPane().add(jLabel68, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 130, 20));

    comboEstiloEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gótico", "Contemporáneo", "Barroco", "Modernista", "Art-Deco" }));
    getContentPane().add(comboEstiloEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 520, 200, -1));

    jLabel69.setBackground(new java.awt.Color(204, 204, 204));
    jLabel69.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel69.setText("Piscina:");
    jLabel69.setOpaque(true);
    getContentPane().add(jLabel69, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 130, 20));

    comboPiscinaEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
    getContentPane().add(comboPiscinaEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 200, -1));

    jLabel70.setBackground(new java.awt.Color(204, 204, 204));
    jLabel70.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel70.setText("Rancho:");
    jLabel70.setOpaque(true);
    getContentPane().add(jLabel70, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 130, 20));

    comboRanchoEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
    getContentPane().add(comboRanchoEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 190, -1));

    jLabel72.setBackground(new java.awt.Color(204, 204, 204));
    jLabel72.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel72.setText("Cantidad parqueo visitas:");
    jLabel72.setOpaque(true);
    getContentPane().add(jLabel72, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, 150, 20));
    getContentPane().add(txtVisitasEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 640, 170, -1));

    jLabel75.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel75.setText("Información de los niveles:");
    getContentPane().add(jLabel75, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 320, -1));

    jLabel74.setBackground(new java.awt.Color(204, 204, 204));
    jLabel74.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel74.setText("Cantidad de residencias:");
    jLabel74.setOpaque(true);
    getContentPane().add(jLabel74, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 150, 20));
    getContentPane().add(txtResidenciasEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 120, -1));

    jLabel66.setBackground(new java.awt.Color(204, 204, 204));
    jLabel66.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel66.setText("Cantidad zonas comunes:");
    jLabel66.setOpaque(true);
    getContentPane().add(jLabel66, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 60, 150, 20));
    getContentPane().add(txtZonasEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 60, 90, -1));

    comboNivelEdificio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comercial", "Residencial" }));
    getContentPane().add(comboNivelEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 120, -1));

    btnAgregarNivelEdificio.setText("Agregar nivel");
    btnAgregarNivelEdificio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAgregarNivelEdificioActionPerformed(evt);
      }
    });
    getContentPane().add(btnAgregarNivelEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 100, 240, -1));

    tablaNivelesEdificio.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Residencias", "Zonas comunes", "Tipo"
      }
    ));
    jScrollPane6.setViewportView(tablaNivelesEdificio);

    getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 400, 100));

    btnEliminarNivel.setText("Eliminar nivel");
    btnEliminarNivel.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarNivelActionPerformed(evt);
      }
    });
    getContentPane().add(btnEliminarNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 220, 120, 30));

    jLabel71.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jLabel71.setText("Imágenes:");
    getContentPane().add(jLabel71, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 320, -1));

    labelImagenEdificio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    getContentPane().add(labelImagenEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 240, 130));

    btnActualizarEdificio.setText("Actualizar");
    btnActualizarEdificio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnActualizarEdificioActionPerformed(evt);
      }
    });
    getContentPane().add(btnActualizarEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 640, 140, 30));

    tablaImagenesEdificio.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "Imagenes"
      }
    ));
    tablaImagenesEdificio.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        tablaImagenesEdificioMouseClicked(evt);
      }
    });
    jScrollPane2.setViewportView(tablaImagenesEdificio);

    getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 270, 100));

    btnBuscarImagenEdificio.setText("Buscar imagen");
    btnBuscarImagenEdificio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarImagenEdificioActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarImagenEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, 120, -1));

    btnEliminarImagenEdificio.setText("Eliminar Imagen");
    btnEliminarImagenEdificio.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnEliminarImagenEdificioActionPerformed(evt);
      }
    });
    getContentPane().add(btnEliminarImagenEdificio, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 140, -1));

    jButton1.setForeground(new java.awt.Color(255, 0, 51));
    jButton1.setText("X");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });
    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 50, -1));
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 680));

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void txtIdEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEdificioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_txtIdEdificioActionPerformed

  private void btnAgregarNivelEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarNivelEdificioActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tablaNivelesEdificio.getModel();
    String registro[] = new String[3];
    registro[0] = txtResidenciasEdificio.getText();
    registro[1] = txtZonasEdificio.getText();
    registro[2] = comboNivelEdificio.getSelectedItem().toString();

    modelo.addRow(registro);

    txtResidenciasEdificio.setText("");
    txtZonasEdificio.setText("");
  }//GEN-LAST:event_btnAgregarNivelEdificioActionPerformed

  private void btnEliminarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarNivelActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tablaNivelesEdificio.getModel();    
    int fila = tablaNivelesEdificio.getSelectedRow();
    modelo.removeRow(fila);
  }//GEN-LAST:event_btnEliminarNivelActionPerformed

  private void btnActualizarEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarEdificioActionPerformed

  }//GEN-LAST:event_btnActualizarEdificioActionPerformed

  private void tablaImagenesEdificioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaImagenesEdificioMouseClicked
    int fila = tablaImagenesEdificio.getSelectedRow();
    TableModel modelo = tablaImagenesEdificio.getModel();
    byte[] archivoImagen = (byte[]) modelo.getValueAt(fila, 0);

    ImageIcon imagenIcon = new ImageIcon(new ImageIcon(archivoImagen).getImage().getScaledInstance(labelImagenEdificio.getWidth(), labelImagenEdificio.getHeight()
      , Image.SCALE_SMOOTH));
  labelImagenEdificio.setIcon(imagenIcon);
  }//GEN-LAST:event_tablaImagenesEdificioMouseClicked

  private void btnBuscarImagenEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarImagenEdificioActionPerformed
    byte[] imagenLote;
    String archivoImagen;
    JFileChooser chooser = new JFileChooser();
    chooser.showOpenDialog(null);

    File archivo = chooser.getSelectedFile();
    archivoImagen = archivo.getAbsolutePath();

    File imagen = new File(archivoImagen);
    FileInputStream fis;

    try {
      fis = new FileInputStream(imagen);

      ByteArrayOutputStream bos = new ByteArrayOutputStream();
      byte[] buffer = new byte[1024];

      for (int j; (j = fis.read(buffer)) != -1;) {
        bos.write(buffer, 0, j);
      }
      imagenLote = bos.toByteArray();
      DefaultTableModel modelo = (DefaultTableModel) tablaImagenesEdificio.getModel();
      modelo.addRow(new Object[]{imagenLote});
    } catch (IOException ex) {
      Logger.getLogger(VistaLote.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_btnBuscarImagenEdificioActionPerformed

  private void btnEliminarImagenEdificioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarImagenEdificioActionPerformed
    DefaultTableModel modelo = (DefaultTableModel) tablaImagenesEdificio.getModel();
    int fila = tablaImagenesEdificio.getSelectedRow();
    modelo.removeRow(fila);
    labelImagenEdificio.setIcon(null);
    labelImagenEdificio.revalidate();
  }//GEN-LAST:event_btnEliminarImagenEdificioActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_jButton1ActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaEdificio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VistaEdificio().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnActualizarEdificio;
  public javax.swing.JButton btnAgregarNivelEdificio;
  public javax.swing.JButton btnBuscarImagenEdificio;
  public javax.swing.JButton btnEliminarImagenEdificio;
  public javax.swing.JButton btnEliminarNivel;
  public javax.swing.JComboBox<String> comboEstadoEdificio;
  public javax.swing.JComboBox<String> comboEstiloEdificio;
  public javax.swing.JComboBox<String> comboModalidadEdificio;
  public javax.swing.JComboBox<String> comboNivelEdificio;
  public javax.swing.JComboBox<String> comboPiscinaEdificio;
  public javax.swing.JComboBox<String> comboRanchoEdificio;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel55;
  public javax.swing.JLabel jLabel56;
  public javax.swing.JLabel jLabel57;
  public javax.swing.JLabel jLabel58;
  public javax.swing.JLabel jLabel59;
  public javax.swing.JLabel jLabel60;
  public javax.swing.JLabel jLabel61;
  public javax.swing.JLabel jLabel62;
  public javax.swing.JLabel jLabel63;
  private javax.swing.JLabel jLabel64;
  private javax.swing.JLabel jLabel65;
  private javax.swing.JLabel jLabel66;
  private javax.swing.JLabel jLabel67;
  private javax.swing.JLabel jLabel68;
  private javax.swing.JLabel jLabel69;
  private javax.swing.JLabel jLabel70;
  private javax.swing.JLabel jLabel71;
  private javax.swing.JLabel jLabel72;
  private javax.swing.JLabel jLabel74;
  private javax.swing.JLabel jLabel75;
  public javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JScrollPane jScrollPane6;
  public javax.swing.JLabel labelImagenEdificio;
  public javax.swing.JTable tablaImagenesEdificio;
  public javax.swing.JTable tablaNivelesEdificio;
  public javax.swing.JTextField txtAlturaEdificio;
  public javax.swing.JTextField txtAreaEdificio;
  public javax.swing.JTextField txtCantonEdificio;
  public javax.swing.JTextField txtConstruccionEdificio;
  public javax.swing.JTextField txtDireccionEdificio;
  public javax.swing.JTextField txtDistritoEdificio;
  public javax.swing.JTextField txtFiscalEdificio;
  public javax.swing.JTextField txtIdEdificio;
  public javax.swing.JTextField txtMetroEdificio;
  public javax.swing.JComboBox<String> txtProvinciaEdificio;
  public javax.swing.JTextField txtResidenciasEdificio;
  public javax.swing.JTextField txtVisitasEdificio;
  public javax.swing.JTextField txtZonasEdificio;
  // End of variables declaration//GEN-END:variables
}
