/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.poo.bieninmueble.vistas;

import com.poo.bieninmueble.controladores.ControladorPrincipal;

/**
 *
 * @author anjel
 */
public class VistaCliente extends javax.swing.JFrame {

    /**
     * Creates new form VistaCliente
     */
    public VistaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtCriterioCliente = new javax.swing.JTextField();
    btnBuscarRango = new javax.swing.JButton();
    jLabel3 = new javax.swing.JLabel();
    txtMayor = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    txtMenor = new javax.swing.JTextField();
    btnBuscarFiltro = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tablaPropiedadesCliente = new javax.swing.JTable();
    btnX = new javax.swing.JButton();
    btnVer = new javax.swing.JButton();
    btnComentario = new javax.swing.JButton();
    comboFiltroCliente = new javax.swing.JComboBox<>();
    btnFicha = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
    jLabel1.setText("Bienvenido/a ");
    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

    jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel2.setText("Filtrar por: ");
    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

    txtCriterioCliente.setText("Escriba el criterio de búsqueda...");
    getContentPane().add(txtCriterioCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 240, 30));

    btnBuscarRango.setText("Buscar precio");
    btnBuscarRango.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarRangoActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarRango, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 120, 30));

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("Filtrar por rango de precio:");
    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 110, 150, -1));

    txtMayor.setText("Mayor");
    getContentPane().add(txtMayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 110, 30));

    jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel4.setText("a");
    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 10, -1));

    txtMenor.setText("Menor");
    getContentPane().add(txtMenor, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 100, 30));

    btnBuscarFiltro.setText("Buscar");
    btnBuscarFiltro.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnBuscarFiltroActionPerformed(evt);
      }
    });
    getContentPane().add(btnBuscarFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 120, 30));

    tablaPropiedadesCliente.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null},
        {null, null, null, null, null}
      },
      new String [] {
        "Identificador", "Provincia", "Tipo", "Modalidad", "Precio"
      }
    ));
    jScrollPane1.setViewportView(tablaPropiedadesCliente);

    getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 690, 140));

    btnX.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btnX.setForeground(new java.awt.Color(255, 51, 0));
    btnX.setText("X");
    btnX.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnXActionPerformed(evt);
      }
    });
    getContentPane().add(btnX, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 60, 30));

    btnVer.setText("Ver propiedad");
    getContentPane().add(btnVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 320, 140, -1));

    btnComentario.setText("Escribir comentario");
    getContentPane().add(btnComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 320, 160, -1));

    comboFiltroCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Modalidad", "Provincia", "Todas" }));
    getContentPane().add(comboFiltroCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 100, -1));

    btnFicha.setText("Solicitar ficha");
    getContentPane().add(btnFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 190, -1));
    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 390));

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarRangoActionPerformed

  private void btnBuscarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarFiltroActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_btnBuscarFiltroActionPerformed

  private void btnXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXActionPerformed
    this.setVisible(false);
    ControladorPrincipal vista = new ControladorPrincipal(new VistaCredenciales());
    vista.vistaPrincipal.setVisible(true);
  }//GEN-LAST:event_btnXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaCliente().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  public javax.swing.JButton btnBuscarFiltro;
  public javax.swing.JButton btnBuscarRango;
  public javax.swing.JButton btnComentario;
  public javax.swing.JButton btnFicha;
  public javax.swing.JButton btnVer;
  public javax.swing.JButton btnX;
  public javax.swing.JComboBox<String> comboFiltroCliente;
  public javax.swing.JLabel jLabel1;
  public javax.swing.JLabel jLabel2;
  public javax.swing.JLabel jLabel3;
  public javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  public javax.swing.JScrollPane jScrollPane1;
  public javax.swing.JTable tablaPropiedadesCliente;
  public javax.swing.JTextField txtCriterioCliente;
  public javax.swing.JTextField txtMayor;
  public javax.swing.JTextField txtMenor;
  // End of variables declaration//GEN-END:variables
}
